### PR TITLE
Completed Authenticity Check

### PR DESCRIPTION
**Pull request by Flori00**
The image and other important values were missing.

### CODE REVIEW

**Comment by Flori00** [comment]
@hleb-albau could you please review my pull request? I need this feature.
Thank you!

**Comment by hleb-albau** [comment]
@Flori00 working on it

**Comment by Flori00** [comment]
Thanks you very much! sry for me being impatient.

**Comment by hleb-albau** [comment]
oh, not a problem
it is just a confirmation, that I took a task

Seems the fields you added in this PR do not belong to all checks. Do you see child classes of AuthenticityCheckResultItem? For example https://github.com/regulaforensics/DocumentReader-web-csharp-client/blob/master/src/Regula.DocumentReader.WebClient/Model/IdentResult.cs

https://github.com/regulaforensics/DocumentReader-web-csharp-client/blob/9780111b69c916056803a05fa0fbbd05de263fb0/src/Regula.DocumentReader.NetCoreExample/Program.cs#L67 Here you can find how to obtains concrete authenticity results.

**Comment by Flori00** [comment]
Ahh ok i will add them, thanks! Yea i already tried to get these, but in the json there are the images and in the sdk they were missing.

**Comment by hleb-albau** [comment]
Hello Flori00,

Could you, please, describe your problem? I can't understand, why we need to add to `AuthenticityCheckResultItem` these fields. `AuthenticityCheckResultItem` is a base class for all **check results**(`FiberChecks`, `IdentChecks`, `ImageIdentChecks`, `OCRSecurityTextChecks`, `SecurityFeatureChecks`). To get concrete check results, use next methods:

```
var docAuthenticity = response.Authenticity();
var docImagePattern = docAuthenticity.ImagePatternChecks();   // IdentChecks
```
See https://github.com/regulaforensics/DocumentReader-web-csharp-client/blob/9780111b69c916056803a05fa0fbbd05de263fb0/src/Regula.DocumentReader.WebClient/Model/Ext/Autheticity/Autheticity.cs#L7 class for details.

**Comment by Flori00** [comment]
ah ok thanks!

**Comment by Flori00** [comment]
So ineed: https://postimg.cc/3ywqLQbR
In the Sdk: https://postimg.cc/5HjPBq6Q
The Type of the Object i need the images is from the type Regula.DocumentReader.WebClient.Model.AuthenticityCheckResultItem
and there i added the new types.

**Comment by hleb-albau** [comment]
Oh, I see. It is another problem here. For some reason, during deserialization client creates base classes instead of concrete, is it right? Could you check in runtime what types are contained in `AuthenticityChecklist.List` array?

**Comment by Flori00** [comment]
Oh this classes should have another class like IdentResult, i see has also the Images?
class AuthenticityChecklist.List -> class AuthenticityCheckResult.List -> class AuthenticityCheckResultItem

**Comment by hleb-albau** [comment]
Also, could you share a bit more code of how you using the client?

**Comment by hleb-albau** [comment]
> Oh this classes should have another class like IdentResult, i see has also the Images?
> class AuthenticityChecklist.List -> class AuthenticityCheckResult.List -> class AuthenticityCheckResultItem

Yes, here should be concrete results instead of `AuthenticityCheckResultItem`

**Comment by Flori00** [comment]
```string apiBaseUrl = ApiBasePath;

            var imageBytes = File.ReadAllBytes(imgpath);
            var image = new ProcessRequestImage(new ImageData(imageBytes), Light.WHITE);

            var requestParams = new RecognitionParams().WithScenario(Scenario.FULL_AUTH);
            requestParams.Log = true;

            var request = new RecognitionRequest(requestParams, image);
            var api = new DocumentReaderApi(apiBaseUrl);

            var response = api.Process(request);

            var status = response.Status();
            var docOverallStatus = (Models.StatusResult)status.OverallStatus;
            var docOpticalTextStatus = (Models.StatusResult)status.DetailsOptical.Text;

            var docAuthenticity = response.Authenticity();```

**Comment by hleb-albau** [comment]
I found the issue root, will fix it in an hour!

**Comment by Flori00** [comment]
k thanks!

**Comment by hleb-albau** [comment]
@Flori00, please, checkout https://github.com/regulaforensics/DocumentReader-web-csharp-client/releases/tag/v5.7.4

**Pull request closed without merging**
